meta_product_name: "BikeEazy"
meta_title: "BikeEazy: Discover your favorite city. Renting a bike for a day or more"
meta_description: "BikeEazy encourages people to rent a bike for a day or more in order to reduce polution and improve the experience of visiting a city."
meta_image: "bikeeazycover.jpg" # should exist in `app/assets/images/`
